import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Database, Plus, Save, ShieldCheck } from "lucide-react";
import { useFinancialYear } from "@/AppContext";
import { api } from "@/lib/api";
import { money } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Loading } from "@/components/Loading";

type Profile = { id: number; name: string; pan: string | null; aadhaar_last4: string | null; mobile: string | null; upi_ids: string[]; customer_ids: string[]; resident: boolean; birth_date: string | null };
type Deduction = { id: number; section: string; description: string; amount_claimed: number; amount_eligible: number; suggested: boolean; accepted: boolean };
type Log = { id: number; created_at: string; level: string; event_type: string; message: string };
type Account = { id: number; name: string; masked_number: string | null; bank: string | null; is_owned: boolean; ownership_confirmed: boolean };

export function SettingsPage() {
  const { financialYear } = useFinancialYear();
  const client = useQueryClient();
  const profile = useQuery({ queryKey: ["profile"], queryFn: () => api<Profile>("/api/profile") });
  const deductions = useQuery({ queryKey: ["deductions", financialYear], queryFn: () => api<Deduction[]>(`/api/deductions?financial_year=${encodeURIComponent(financialYear)}`) });
  const logs = useQuery({ queryKey: ["logs"], queryFn: () => api<Log[]>("/api/audit-logs?limit=50"), refetchInterval: 10_000 });
  const accounts = useQuery({ queryKey: ["accounts"], queryFn: () => api<Account[]>("/api/accounts") });
  const [profileForm, setProfileForm] = useState<Partial<Profile>>({});
  const [newDeduction, setNewDeduction] = useState({ section: "80C", description: "", amount: "" });
  const saveProfile = useMutation({ mutationFn: () => api("/api/profile", { method: "PATCH", body: JSON.stringify(profileForm) }), onSuccess: () => { setProfileForm({}); client.invalidateQueries({ queryKey: ["profile"] }); } });
  const addDeduction = useMutation({ mutationFn: () => api("/api/deductions", { method: "POST", body: JSON.stringify({ financial_year: financialYear, section: newDeduction.section, description: newDeduction.description, amount_claimed: Number(newDeduction.amount), accepted: true }) }), onSuccess: () => { setNewDeduction({ section: "80C", description: "", amount: "" }); client.invalidateQueries({ queryKey: ["deductions"] }); client.invalidateQueries({ queryKey: ["dashboard"] }); } });
  const toggleDeduction = useMutation({ mutationFn: ({ id, accepted }: { id: number; accepted: boolean }) => api(`/api/deductions/${id}?accepted=${accepted}`, { method: "PATCH" }), onSuccess: () => { client.invalidateQueries({ queryKey: ["deductions"] }); client.invalidateQueries({ queryKey: ["dashboard"] }); } });
  const confirmAccount = useMutation({ mutationFn: ({ id, is_owned }: { id: number; is_owned: boolean }) => api(`/api/accounts/${id}`, { method: "PATCH", body: JSON.stringify({ is_owned }) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["accounts"] }); client.invalidateQueries({ queryKey: ["dashboard"] }); } });

  if (profile.isLoading) return <Loading label="Loading local settings" />;
  const current = { ...profile.data, ...profileForm } as Profile;
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold tracking-tight">Settings</h1><p className="mt-1 text-sm text-muted-foreground">Identity signals improve self-transfer matching. Sensitive values remain local.</p></div>
    <div className="grid gap-5 xl:grid-cols-2">
      <Card><CardHeader><CardTitle>Taxpayer profile</CardTitle><CardDescription>PAN, mobile, UPI and customer IDs are matching signals; passwords are never stored.</CardDescription></CardHeader><CardContent><form className="grid gap-4 sm:grid-cols-2" onSubmit={(event) => { event.preventDefault(); saveProfile.mutate(); }}><Field label="Name"><Input value={current.name || ""} onChange={(event) => setProfileForm((value) => ({ ...value, name: event.target.value }))} /></Field><Field label="PAN"><Input maxLength={10} value={current.pan || ""} onChange={(event) => setProfileForm((value) => ({ ...value, pan: event.target.value.toUpperCase() }))} /></Field><Field label="Mobile"><Input value={current.mobile || ""} onChange={(event) => setProfileForm((value) => ({ ...value, mobile: event.target.value }))} /></Field><Field label="Birth date"><Input type="date" value={current.birth_date || ""} onChange={(event) => setProfileForm((value) => ({ ...value, birth_date: event.target.value }))} /></Field><Field label="UPI IDs (comma separated)" className="sm:col-span-2"><Input value={(current.upi_ids || []).join(", ")} onChange={(event) => setProfileForm((value) => ({ ...value, upi_ids: event.target.value.split(",").map((item) => item.trim()).filter(Boolean) }))} /></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={current.resident ?? true} onChange={(event) => setProfileForm((value) => ({ ...value, resident: event.target.checked }))} /> Resident individual</label><div className="sm:text-right"><Button type="submit" disabled={saveProfile.isPending}><Save className="h-4 w-4" /> Save profile</Button></div></form></CardContent></Card>
      <Card><CardHeader><CardTitle>Deductions · {financialYear}</CardTitle><CardDescription>Accept evidence suggestions or add verified claims manually.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="grid gap-2 sm:grid-cols-[110px_1fr_140px_auto]"><select className="h-10 rounded-lg border bg-background px-3 text-sm" value={newDeduction.section} onChange={(event) => setNewDeduction((value) => ({ ...value, section: event.target.value }))}>{["80C","80CCD(1B)","80D","80DD","80E","80EE","80EEA","80G","80GG","80TTA","80TTB","80U","80CCD(2)"].map((section) => <option key={section}>{section}</option>)}</select><Input placeholder="Evidence / description" value={newDeduction.description} onChange={(event) => setNewDeduction((value) => ({ ...value, description: event.target.value }))} /><Input type="number" min="0" placeholder="Amount" value={newDeduction.amount} onChange={(event) => setNewDeduction((value) => ({ ...value, amount: event.target.value }))} /><Button disabled={!newDeduction.description || !newDeduction.amount || addDeduction.isPending} onClick={() => addDeduction.mutate()}><Plus className="h-4 w-4" /></Button></div><div className="max-h-80 space-y-2 overflow-y-auto pr-1">{(deductions.data ?? []).map((item) => <div key={item.id} className="flex items-center gap-3 rounded-lg border p-3"><input type="checkbox" checked={item.accepted} onChange={(event) => toggleDeduction.mutate({ id: item.id, accepted: event.target.checked })} /><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="font-medium">{item.section}</p>{item.suggested && <Badge className="bg-muted">Suggested</Badge>}</div><p className="truncate text-xs text-muted-foreground">{item.description}</p></div><p className="font-semibold">{money(item.amount_eligible)}</p></div>)}{!deductions.data?.length && <p className="py-8 text-center text-sm text-muted-foreground">No deductions recorded.</p>}</div></CardContent></Card>
    </div>
    <Card><CardHeader><CardTitle>Account ownership</CardTitle><CardDescription>Self-transfer exclusion remains disabled until both participating accounts are explicitly confirmed as yours.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{(accounts.data ?? []).map((account) => <label key={account.id} className="flex items-center gap-3 rounded-lg border p-3"><input type="checkbox" checked={account.is_owned && account.ownership_confirmed} onChange={(event) => confirmAccount.mutate({ id: account.id, is_owned: event.target.checked })} /><div className="min-w-0 flex-1"><p className="truncate font-medium">{account.name}</p><p className="text-xs text-muted-foreground">{account.bank || "Institution unconfirmed"} · {account.masked_number || "Account number unavailable"}</p></div>{account.ownership_confirmed ? <Badge>{account.is_owned ? "Mine" : "Not mine"}</Badge> : <Badge className="border-amber-500/40 text-amber-700">Confirm</Badge>}</label>)}{!accounts.data?.length && <p className="text-sm text-muted-foreground">No imported accounts yet.</p>}</CardContent></Card>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Database className="h-5 w-5" />Local audit log</CardTitle><CardDescription>Imports, errors, warnings, password requests, duplicates and recovery events.</CardDescription></CardHeader><CardContent><div className="max-h-96 overflow-y-auto rounded-lg border"><table className="w-full min-w-[720px] text-sm"><thead className="sticky top-0 bg-muted"><tr><th className="p-3 text-left">Time</th><th className="p-3 text-left">Level</th><th className="p-3 text-left">Event</th><th className="p-3 text-left">Message</th></tr></thead><tbody>{(logs.data ?? []).map((log) => <tr key={log.id} className="border-t"><td className="whitespace-nowrap p-3 text-xs text-muted-foreground">{new Date(log.created_at).toLocaleString("en-IN")}</td><td className="p-3"><Badge className={log.level === "ERROR" ? "border-red-500/40 text-red-700" : log.level === "WARNING" ? "border-amber-500/40 text-amber-700" : "bg-muted"}>{log.level}</Badge></td><td className="p-3">{log.event_type}</td><td className="p-3 text-muted-foreground">{log.message}</td></tr>)}</tbody></table></div><div className="mt-4 flex items-center gap-2 rounded-lg bg-primary/5 p-3 text-xs text-muted-foreground"><ShieldCheck className="h-4 w-4 text-primary" /> Optional database encryption is available when SQLCipher is installed and ITR_DB_KEY is set.</div></CardContent></Card>
  </div>;
}

function Field({ label, className = "", children }: { label: string; className?: string; children: React.ReactNode }) { return <label className={className}><span className="mb-1 block text-sm font-medium">{label}</span>{children}</label>; }
